### ISSUE TITLE
On Windows 7: Fatal error: spawn ENOENT

### ISSUE THREAD

**Issue by saada** [colinwren/generator-sails#1]
```
Running "server" task

Running "clean:server" (clean) task
Cleaning ".tmp"...OK

Running "concurrent:server" (concurrent) task

Running "coffee:dist" (coffee) task

Running "compass:server" (compass) task
directory .tmp/styles/
create .tmp/styles/main.css

Running "livereload-start" task
... Starting Livereload server on 35729 ...

Running "connect:livereload" (connect) task
Starting connect web server on localhost:9000.

Running "sails:dist" (sails) task
Starting sails server

Running "open:server" (open) task

Running "watch" task
Watching app/scripts/{,*/}*.coffee
Watching test/spec/{,*/}*.coffee
Watching app/styles/{,*/}*.{scss,sass}
Watching app/*.html,{.tmp,app}/styles/{,*/}*.css,{.tmp,app}/scripts/{,*/}*.js,app/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}
Fatal error: spawn ENOENT
```

**Comment by colinwren** [comment]
Ahh this is a problem with grunt-sails, I forgot that spawn has problems with windows, ill switch it out with grunt.util.spwan real quick. Thanks!

**Comment by saada** [comment]
Thank YOU! :smile:

**Comment by colinwren** [comment]
Ok it should be working on windows now after:
https://github.com/colinwren/grunt-sails/commit/3944278374e374dabc5828362f6bec37a9b9cc86

Sorry about that!

**Comment by saada** [comment]
I updated my source and nothing changed. I checked my `node_modules/grunt-sails/tasks/sails.js` and it corresponds to the new changes you made. It seems that the error might be coming from somewhere else?

**Comment by colinwren** [comment]
:frowning: hmm, can you try running `grunt sails` and paste the stack trace? That is the only custom part of `grunt server` and so unless there are problems with yeoman or sails for windows, it must be the culprit.

**Comment by saada** [comment]
```
Running "sails:dist" (sails) task
Starting sails server

Done, without errors.
```

Windows FAIL

**Comment by colinwren** [comment]
hmm, I think it is a problem with `forever` have you used `forever` to run sails before?

**Comment by saada** [comment]
Nope :(

**Comment by colinwren** [comment]
and you are getting the same 

```
Fatal error: spawn ENOENT
```

when you run

```
grunt server
```

after you have the new version of grunt sails?

Thanks so much for helping with this!

**Comment by saada** [comment]
Yes sir! Same error

**Comment by colinwren** [comment]
It actually looks like its a problem with watch now that i look at the stacktrace more, can you change the `server` task at the bottom of the gruntfile by commenting out watch like this:

``` javascript
grunt.registerTask('server', function (target) {
        //if (target === 'dist') {
            //return grunt.task.run(['build', 'open', 'connect:dist:keepalive']);
        //}

        grunt.task.run([
            'clean:server',
            'concurrent:server',
            'livereload-start',
            'connect:livereload',
            'sails',
            'open'
          /// 'watch' /////comment this out
        ]);
    });
```

**Comment by saada** [comment]
```
Running "server" task

Running "clean:server" (clean) task
Cleaning ".tmp"...OK

Running "concurrent:server" (concurrent) task

Running "coffee:dist" (coffee) task

Running "compass:server" (compass) task
directory .tmp/styles/
   create .tmp/styles/main.css

Running "livereload-start" task
... Starting Livereload server on 35729 ...

Running "connect:livereload" (connect) task
Starting connect web server on localhost:9000.

Running "sails:dist" (sails) task
Starting sails server

Running "open:server" (open) task

Done, without errors.
```

I also tried `sails lift` and that works just fine...

**Comment by colinwren** [comment]
have you used `yo webapp` recently and run grunt server?

**Comment by saada** [comment]
OK maybe I should give more details on what I did exactly:
`yo sails` followed by `grunt server`.
Now I just tried `yo webapp` and `grunt server` and _NO PROBLEMS AT ALL_

**Comment by colinwren** [comment]
damn, I literally copied the yeoman webapp generator and added grunt-sails with forever, can you run `grunt watch` in the yo-sail directory

**Comment by saada** [comment]
Dude, thank you for your patience in helping solve this bug!

`grunt watch` worked with no problems

**Comment by saada** [comment]
Are you using the latest yeoman `1.0.0-beta.4`?

**Comment by colinwren** [comment]
in `node_modules/grunt-sails/tasks/sails.js` can you change the grunt util spawn to this:

``` javascript
    grunt.util.spawn({
      cmd: 'sails',
      args: ['lift'],
      opts: {
        stdio: 'inherit'
      }
    }, function (error, result) {
      if (error) {
        grunt.fail.fatal(result.stdout);
      }
      grunt.log.writeln(result.stdout);
      done();
    });
```

Thanks for helping fix this!

Yeah i am using `1.0.0-beta.4`
you mean the output of 

```
yo -v
```

right?

**Comment by saada** [comment]
Correct! 
And as for the snippet you sent me, :smile: :dancers: 
Bug fixed!

**Comment by colinwren** [comment]
YAY!! unfortunately running it like that doesn't restart the server when you make changes to api files :frowning: can you install forever:

```
npm install -g forever
```

and change that snippet to 

```
    grunt.util.spawn({
      cmd: 'forever',
      args: ['-w', 'app.js'],
      opts: {
        stdio: 'inherit'
      }
    }, function (error, result) {
      if (error) {
        grunt.fail.fatal(result.stdout);
      }
      grunt.log.writeln(result.stdout);
      done();
    });
```

Thanks!

**Comment by saada** [comment]
Okay, it runs with no errors.. it opens up the sails default page... what behavior should I be expecting exactly? Also, which view should grunt autoupdate? The public folder? or the sails views?

**Comment by colinwren** [comment]
It should open the default page, the livereload isnt working because sails is using dynamic views so you cant have the build step that appends the livereload snipped to the html. change some of the coffeescript in app/scripts/hello.js and it will autocompile and when you refresh the default page it will be loaded

**Comment by colinwren** [comment]
you can get livereload working by using this chrome extension 
https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en

**Comment by saada** [comment]
gotcha.. it works fine...

**Comment by saada** [comment]
Hey, Can you join me here: http://balloons.io/73228b

**Comment by jitendravyas** [comment]
I'm getiting this error in windows 7 'spawn ENOENT Use --force to continue'

**Comment by spacebeers** [comment]
I'm getting the same error as @jitendravyas. I'll try it off Windows and see where I end up .
