### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by yoshuawuyts** [colinwren/generator-sails#3]
Hey, is this package still maintained? Last update was over 2 months ago. Imho integrating sails with yeoman should be high on the priority list.

**Comment by colinwren** [comment]
I haven't had time to work on this package recently. I think using sails with yeoman is awesome! Sails is currently working on grunt integration, and in the process, removing asset rack. This will make yeoman integration much easier.

If your interested in updating and maintaining this package ill give you commit access and npm ownership.

**Comment by yoshuawuyts** [comment]
Awesome, I'm very much interested in pushing updates. Getting 0.9 compatibility would be first up.
